version: 2.1
jobs:
  build:
    working_directory: ~/circleci-java
    docker:
      - image: circleci/openjdk:17-jdk-buster
    environment:
      MAVEN_OPTS: "-Djdk.lang.Process.launchMechanism=vfork"
    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline # gets the project dependencies
      - save_cache:
          paths:
            - ~/.m2
            - target
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}-{{ .Branch }}
      - run: mvn package
  publish_image:
    docker:
      - image: circleci/openjdk:17-jdk-bullseye
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.12"
      - restore_cache:
          keys:
            - circleci-demo-java-spring-{{ checksum "pom.xml" }}-{{ .Branch }}
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run: docker context create buildx
      - run: docker buildx create --name buildx --use buildx
      - run: docker login -u "$QUAY_LOGIN" -p "$QUAY_PASSWORD" quay.io
      - run: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - run: |
          tags=(master main)
          if [[ -n "$CIRCLE_TAG" ]]; then
            tags+=("${CIRCLE_TAG}" latest)
          fi

          set -x
          docker buildx build \
            --progress plain \
            --platform "$BUILDX_PLATFORMS" \
            "${tags[@]/#/--tag=quay.io/prometheus/cloudwatch-exporter:}" \
            "${tags[@]/#/--tag=prom/cloudwatch-exporter:}" \
            --push .

      - run: |
          tags=(minimal)
          if [[ -n "$CIRCLE_TAG" ]]; then
            tags+=("${CIRCLE_TAG}-minimal" latest-minimal)
          fi

          set -x
          docker buildx build \
            --dockerfile Dockerfile-minimal \
            --progress plain \
            --platform "$BUILDX_PLATFORMS" \
            "${tags[@]/#/--tag=quay.io/prometheus/cloudwatch-exporter:}" \
            "${tags[@]/#/--tag=prom/cloudwatch-exporter:}" \
            --push .

      - run: docker images
  build_image:
    docker:
      - image: circleci/openjdk:17-jdk-bullseye
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.12"
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run: docker context create buildx
      - run: docker buildx create --name buildx --use buildx
      - run: |
          docker buildx build \
            --progress plain \
            --platform "$BUILDX_PLATFORMS" \
            .
      - run: |
          docker buildx build \
            --dockerfile Dockerfile-minimal \
            --progress plain \
            --platform "$BUILDX_PLATFORMS" \
            .
workflows:
  version: 2
  cloudwatch_exporter:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build_image:
          context: org-context
          requires:
            - build
          filters:
            branches:
              ignore: master
      - publish_image:
          context: org-context
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: master

orbs:
  prometheus: prometheus/prometheus@0.14.0
